apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "deployment.fullname" . }}
  labels:
    app: {{ template "deployment.name" . }}
    chart: {{ template "deployment.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "deployment.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "deployment.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: {{ .Values.applicationInsights.InstrumentationKey }}
